name: Update Homebrew Formula (Manual)

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag (e.g., v1.0.5)'
        required: true
        default: 'v1.0.5'

jobs:
  update-homebrew:
    runs-on: ubuntu-latest
    steps:
      - name: Calculate SHA256
        id: sha256
        run: |
          TARBALL_URL="https://github.com/sutaminajing40/multi-claude/archive/refs/tags/${{ github.event.inputs.version }}.tar.gz"
          SHA256=$(curl -sL "$TARBALL_URL" | sha256sum | cut -d' ' -f1)
          
          echo "TARBALL_URL=$TARBALL_URL" >> $GITHUB_OUTPUT
          echo "SHA256=$SHA256" >> $GITHUB_OUTPUT
          
          echo "Version: ${{ github.event.inputs.version }}"
          echo "URL: $TARBALL_URL"
          echo "SHA256: $SHA256"

      - name: Create dispatch event
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.HOMEBREW_GITHUB_TOKEN }}" \
            https://api.github.com/repos/sutaminajing40/homebrew-multi-claude/dispatches \
            -d '{
              "event_type": "update-formula",
              "client_payload": {
                "version": "${{ github.event.inputs.version }}",
                "url": "${{ steps.sha256.outputs.TARBALL_URL }}",
                "sha256": "${{ steps.sha256.outputs.SHA256 }}"
              }
            }'